### DISCUSSION TITLE
Chain Migration Sites - Community Guide

### DISCUSSION THREAD

**Discussion by AbdelStark** [keep-starknet-strange/manlettostarknet#3] [Ideas]
# Chain Migration Sites - Community Guide

## Overview
We're creating a series of websites to encourage users from various chains to try Starknet. Each site follows the manlettostarknet.com template but with chain-specific memes and content.

### 1. Domain Name
- Should include a recognizable meme/term from source chain
- Format: `[chainMeme]tostarknet.com`
- Example: `manlettostarknet.com` for Solana

### 2. Required Elements
- Hero catchphrase
- Migration message
- Bridge instructions
- Getting started resources
- Ecosystem highlights

### ZkSync Era
- Domain: `zktrademarktostarknet.com`
- Catchphrase: "Done with the ™️? Time for true zkrollups"
- Memes: TM symbol, patent/trademark jokes

### Aptos/Sui (Move)
- Domain: `movetostarknet.com`
- Catchphrase: "Stop Moving in circles, start STARKing"
- Focus: Move developers, parallel execution fans

### Base
- Domain: `basedtostarknet.com`
- Catchphrase: "Get truly BASED on Starknet"
- Theme: Blue -> Pink transition

### Sui
- Domain: `suigentostarknet.com`
- Theme: Fast-food/restaurant analogies
- Focus: Object model developers

### Domain Names
- Keep it memorable
- Include ecosystem meme
- Keep it friendly, avoid hostile terms

### Content Suggestions
```yaml
chain_name: "Chain Name"
domain: "memestostarknet.com"
catchphrase: "Main catchphrase"
memes:
  - "Meme reference 1"
  - "Meme reference 2"
migration_hooks:
  - "Why they should migrate"
  - "What appeals to their devs"
resources:
  bridge_link: "URL"
  starter_guide: "URL"
  ecosystem_highlights: "URL"
```

### Implementation
1. Fork manlettostarknet.com
2. Update content & branding
3. Deploy to domain

## Submit Ideas
Open PR with above template filled for your target chain.
